name: conda_dependencies
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6.2

- pip:
  # You must list azureml-defaults as a pip dependency
  - azureml-defaults>=1.0.45
  - numpy
  - tensorflow==2.0.0
  - keras<=2.3.1
  - matplotlib
  - pickle4
  - joblib
channels:
- conda-forge